export const INCIDENT_LIST_REQUEST = 'INCIDENT_LIST_REQUEST'
export const INCIDENT_LIST_SUCCESS = 'INCIDENT_LIST_SUCCESS'
export const INCIDENT_LIST_FAIL = 'INCIDENT_LIST_FAIL'

export const INCIDENT_DETAILS_REQUEST = 'INCIDENT_DETAILS_REQUEST'
export const INCIDENT_DETAILS_SUCCESS = 'INCIDENT_DETAILS_SUCCESS'
export const INCIDENT_DETAILS_FAIL = 'INCIDENT_DETAILS_FAIL'

export const INCIDENT_LIST_MY_REQUEST = 'INCIDENT_LIST_MY_REQUEST'
export const INCIDENT_LIST_MY_SUCCESS = 'INCIDENT_LIST_MY_SUCCESS'
export const INCIDENT_LIST_MY_FAIL = 'INCIDENT_LIST_MY_FAIL'
export const INCIDENT_LIST_MY_RESET = 'INCIDENT_LIST_MY_RESET'

export const INCIDENT_SUBMIT_REQUEST = 'INCIDENT_SUBMIT_REQUEST'
export const INCIDENT_SUBMIT_SUCCESS = 'INCIDENT_SUBMIT_SUCCESS'
export const INCIDENT_SUBMIT_FAIL = 'INCIDENT_SUBMIT_FAIL'
